module.exports = Object.freeze({
  workspaceAssessment: {
    enums: {
      assessmentNames: {
        CHANGE_VISION_CASE: "Change Vision/Case for Change",
        CHANGE_APPROACH_STRATEGY: "Change Approach/Strategy",
        CHANGE_IMPACT_ASSESSMENT: "Change Impact Assessment",
        STAKEHOLDER_ASSESSMENT_MAP: "Stakeholder Assessment/Map",
        TRAINING_NEEDS_ASSESSMENT: "Training Needs Assessment",
        BENEFITS: "Benefits",
        TRANSITION_TO_SUSTAIN: "Transition to Sustain",
        ADKAR_ASSESSMENT: "ADKAR Assessment",
        WHATS_CHANGING_SUMMARY: "What’s Changing and What is Not - Summary",
        TRAINING_PLAN: "Training Plan",
        COMMUNICATIONS_PLAN: "Communications Plan",
        ENGAGEMENT_CHANGE_PLAN: "Engagement & Change Plan",
        READINESS_ASSESSMENT: "Readiness Assessment",
        HEALTH_CHECK: "Health Check",
        MANAGING_RESISTANCE: "Managing Resistance",
        KEY_MESSAGES_BY_GROUP: "Key Messages by Stakeholder Group",
        BRIEFING_MESSAGES: "Briefing Messages",
        COMMUNICATIONS_MESSAGES: "Communications Messages",
        FAQS: "FAQ’s",
        CHAMPIONS_SURVEY: "Champions Survey",
        USER_FEEDBACK_SURVEY: "User Feedback Survey",
        TRAINING_FEEDBACK_SURVEY: "Training Feedback Survey",
        POST_GO_LIVE_FEEDBACK: "Post Go Live Feedback Survey",
        CHANGE_KPIS_USER_ADOPTION: "Change KPIs/User Adoption Statistics",
      },
      assessmentStatus: {
        PENDING: "pending",
        IN_PROGRESS: "in-progress",
        COMPLETED: "completed",
      },
    },
  },
});
